import {
  IOSConfig,
  WarningAggregator,
  withAppDelegate,
  withInfoPlist,
  type ConfigPlugin,
  type ExportedConfigWithProps,
} from '@expo/config-plugins';
import eol from 'eol';
import type { AppDelegateProjectFile } from '@expo/config-plugins/build/ios/Paths';

/*
 * Mods for Info.plist
 */
export const withExpoBraintreePlist: ConfigPlugin = (expoConfig) => {
  return withInfoPlist(expoConfig, (config) => {
    const bundleIdentifier = config.ios?.bundleIdentifier ?? '';
    const bundleIdentifierWithBraintreeSchema = `${bundleIdentifier}.braintree`;
    const bundleUrlTypes = config.modResults.CFBundleURLTypes ?? [];

    // Check if an entry with the specific Braintree URL scheme already exists
    const isBraintreeEntryNotExist = !bundleUrlTypes.find((urlType) => {
      return urlType.CFBundleURLSchemes?.includes(
        bundleIdentifierWithBraintreeSchema
      );
    });

    // If Braintree entry doesn't exist, add a new one
    if (isBraintreeEntryNotExist) {
      bundleUrlTypes.push({
        CFBundleURLSchemes: [bundleIdentifierWithBraintreeSchema],
      });
    }

    // Assign the modified bundleUrlTypes back to the config
    config.modResults.CFBundleURLTypes = bundleUrlTypes;

    return config;
  });
};

/*
 * Add allowlist Venmo URL scheme
 * @see https://developer.paypal.com/braintree/docs/guides/venmo/client-side/ios/v6#allowlist-venmo-url-scheme
 */
export const withVenmoScheme: ConfigPlugin = (expoConfig) => {
  return withInfoPlist(expoConfig, (config) => {
    // Ensure LSApplicationQueriesSchemes exists in Info.plist
    config.modResults.LSApplicationQueriesSchemes =
      config.modResults.LSApplicationQueriesSchemes || [];

    // Hardcoded scheme for Venmo
    const venmoScheme = 'com.venmo.touch.v2';

    // Add the Venmo scheme to the LSApplicationQueriesSchemes array if not already present
    if (!config.modResults.LSApplicationQueriesSchemes.includes(venmoScheme)) {
      config.modResults.LSApplicationQueriesSchemes.push(venmoScheme);
    }

    return config;
  });
};

/**
 * Mods for AppDelegate.swift React Native above 0.77.x and Expo above 53
 */
export const modifyAppDelegateSwift = (
  config: ExportedConfigWithProps<AppDelegateProjectFile>
) => {
  const appDelegate = config.modResults;
  let contents = eol.split(appDelegate.contents);

  // Step 1 Add method to properly handle openUrl method in AppDelegate.swift
  const openUrlIdentifier = `options: [UIApplication.OpenURLOptionsKey: Any] = [:]`;

  const expoBraintreeConfigHandleUrl = `return ExpoBraintreeConfig.handleUrl(url: url)`;
  const expoBraintreeOpenUrlLines = [
    `    // @generated by react-native-expo-braintree (DO NOT MODIFY)`,
    `    if url.scheme?.localizedCaseInsensitiveCompare(`,
    `      ExpoBraintreeConfig.paymentURLScheme`,
    `    ) == .orderedSame {`,
    `      ${expoBraintreeConfigHandleUrl}`,
    `    }`,
    `    // @generated by react-native-expo-braintree (DO NOT MODIFY)`,
  ];
  const openUrlIdentifierElementIndex = contents.findIndex((content) =>
    content.includes(openUrlIdentifier)
  );

  // Step 2 If openUrlIdentifierElementIndex exist in AppDelegate.swift then we only need to add expoBraintreeOpenUrlLines at the top of that method
  if (openUrlIdentifierElementIndex !== -1) {
    contents.splice(
      // We are adding +2 to the index to insert content after ') -> Bool {' block
      openUrlIdentifierElementIndex + 2,
      0,
      ...expoBraintreeOpenUrlLines
    );
  }
  // Step 3 If openUrlIdentifierElementIndex do not exist in AppDelegate.swift add a warning that something went wrong
  else {
    WarningAggregator.addWarningIOS(
      'withExpoBraintree',
      `Unable to find "options: [UIApplication.OpenURLOptionsKey: Any] = [:]" in AppDelegate.swift, automatic changes not applied expo-braintree might not working as expected`
    );
  }

  const expoBraintreeConfigHandleUrlElementIndex = contents.findIndex(
    (content) => content.includes(expoBraintreeConfigHandleUrl)
  );

  if (expoBraintreeConfigHandleUrlElementIndex === -1) {
    WarningAggregator.addWarningIOS(
      'withExpoBraintree',
      `Unable to find "return ExpoBraintreeConfig.handleUrl(url: url)" in AppDelegate.swift, automatic changes not applied expo-braintree might not working as expected`
    );
  }
  return contents;
};

export const withExpoBraintreeAppDelegate: ConfigPlugin = (expoConfig) => {
  return withAppDelegate(expoConfig, (config) => {
    const appDelegateLanguage = config.modResults.language;
    if (appDelegateLanguage === 'swift') {
      const resultSwift = modifyAppDelegateSwift(config);
      config.modResults.contents = resultSwift.join('\n');
    } else {
      WarningAggregator.addWarningIOS(
        'withExpoBraintree',
        `Objective-C/Objective-C++ AppDelegate (${appDelegateLanguage}) is not supported in version 4.0.0. Please upgrade your project to a Swift AppDelegate.`
      );
    }
    return config;
  });
};

// Add a new wrapper Swift file to the Xcode project for Swift compatibility.
export const withBraintreeWrapperFile: ConfigPlugin = (config) => {
  const braintreeWrapperSwift = [
    'import Braintree',
    'import Foundation',
    '',
    'public final class ExpoBraintreeConfig {',
    '',
    ' private init() {}',
    '',
    ' public static var paymentURLScheme: String {',
    '   let bundleIdentifier = Bundle.main.bundleIdentifier ?? ""',
    '   return bundleIdentifier + ".braintree"',
    ' }',
    '',
    ' public static func handleUrl(url: URL) -> Bool {',
    '   return BTAppContextSwitcher.sharedInstance.handleOpen(url)',
    ' }',
    '}',
  ];

  return IOSConfig.XcodeProjectFile.withBuildSourceFile(config, {
    filePath: 'ExpoBraintreeConfig.swift',
    contents: braintreeWrapperSwift.join('\n'),
  });
};
