package com.expobraintree

enum class EXCEPTION_TYPES(val value: String) {
  KOTLIN_EXCEPTION("ExpoBraintree:`KotlinException"),
  USER_CANCEL_EXCEPTION("ExpoBraintree:`UserCancelException"),
  TOKENIZE_EXCEPTION("ExpoBraintree:`TokenizeException"),
  PAYPAL_DISABLED_IN_CONFIGURATION("ExpoBraintree:`Paypal disabled in configuration")
}

enum class ERROR_TYPES(val value: String) {
  API_CLIENT_INITIALIZATION_ERROR("API_CLIENT_INITIALIZATION_ERROR"),
  TOKENIZE_VAULT_PAYMENT_ERROR("TOKENIZE_VAULT_PAYMENT_ERROR"),
  USER_CANCEL_TRANSACTION_ERROR("USER_CANCEL_TRANSACTION_ERROR"),
  PAYPAL_DISABLED_IN_CONFIGURATION_ERROR("PAYPAL_DISABLED_IN_CONFIGURATION_ERROR"),
  DATA_COLLECTOR_ERROR("DATA_COLLECTOR_ERROR"),
  CARD_TOKENIZATION_ERROR("CARD_TOKENIZATION_ERROR"),
  D_SECURE_CARD_TOKENIZATION_ERROR("D_SECURE_CARD_TOKENIZATION_ERROR"),
  D_SECURE_CARD_TOKENIZATION_VALIDATION_ERROR("D_SECURE_CARD_TOKENIZATION_VALIDATION_ERROR"),
  D_SECURE_NOT_ABLE_TO_SHIFT_LIABILITY("D_SECURE_NOT_ABLE_TO_SHIFT_LIABILITY"),
  D_SECURE_LIABILITY_NOT_SHIFTED("D_SECURE_LIABILITY_NOT_SHIFTED"),
  PAYMENT_3D_SECURE_FAILED("PAYMENT_3D_SECURE_FAILED"),
  PAYMENT_3D_SECURE_CANCELLED("PAYMENT_3D_SECURE_CANCELLED"),
}

